from __future__ import annotations

import argparse
import json
import os
import subprocess
import sys
import threading
import traceback
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

# This allows the script to import shared pipeline helpers from common/ even when it is executed from a different working directory.
PIPELINE_ROOT = Path(__file__).resolve().parents[1]
if str(PIPELINE_ROOT) not in sys.path:
    sys.path.insert(0, str(PIPELINE_ROOT))

from common.config import load_json_config, require_keys
from common.io_utils import write_json
from common.naming import sanitize_name_component
from common.terminal_logging import default_step_log_path, terminal_log


# This schema version identifies the raw Snort execution metadata written by Step 21.
RUN_SCHEMA_VERSION = "snort_raw_run_v2"


# These are artifacts managed by Step 21 or by the Snort output mode used by Step 21.
# They are removed before each run so Snort cannot append new alerts to stale files.
MANAGED_OUTPUT_FILES = {
    "alert_json.txt",
    "command.json",
    "execution_metadata.json",
    "stderr.log",
    "stdout.log",
}
MANAGED_OUTPUT_PATTERNS = (
    "alerts__*.json",
)


# This function returns the current UTC timestamp in ISO 8601 format for reproducible execution metadata.
def utc_now() -> str:
    return datetime.now(timezone.utc).isoformat()


# This function returns a compact UTC minute timestamp for POST output run folders.
def utc_minute_timestamp_for_path() -> str:
    return datetime.now(timezone.utc).strftime("%Y%m%d-%H%M")


# This function builds the experiment root directory from the experiment output_root and experiment_id fields in the config.
def build_experiment_root(config: dict[str, Any]) -> Path:
    experiment = config["experiment"]
    return Path(experiment["output_root"]).expanduser() / experiment["experiment_id"]


# This function resolves a path without requiring the final path to already exist.
def resolve_path_for_safety(path: str | Path) -> Path:
    return Path(path).expanduser().resolve(strict=False)


# This function validates that a target path stays inside the active experiment root before Step 21 deletes managed artifacts.
def assert_path_inside_experiment_root(target_path: str | Path, experiment_root: str | Path) -> None:
    resolved_target = resolve_path_for_safety(target_path)
    resolved_root = resolve_path_for_safety(experiment_root)
    try:
        resolved_target.relative_to(resolved_root)
    except ValueError as error:
        raise ValueError(
            f"Refusing to prepare Step 21 output outside experiment root: "
            f"target={resolved_target} experiment_root={resolved_root}"
        ) from error


# This function removes only Step 21/Snort artifacts known to be regenerated by one run.
def prepare_clean_output_dir(output_dir: Path, experiment_root: Path) -> list[str]:
    assert_path_inside_experiment_root(output_dir, experiment_root)
    output_dir.mkdir(parents=True, exist_ok=True)

    removed: list[str] = []
    candidates: list[Path] = [output_dir / filename for filename in sorted(MANAGED_OUTPUT_FILES)]
    for pattern in MANAGED_OUTPUT_PATTERNS:
        candidates.extend(sorted(output_dir.glob(pattern)))

    seen: set[Path] = set()
    for candidate in candidates:
        resolved_candidate = resolve_path_for_safety(candidate)
        if resolved_candidate in seen:
            continue
        seen.add(resolved_candidate)
        assert_path_inside_experiment_root(resolved_candidate, experiment_root)
        if not candidate.exists():
            continue
        if not candidate.is_file():
            raise ValueError(f"Refusing to delete non-file Step 21 managed artifact: {candidate}")
        candidate.unlink()
        removed.append(str(candidate))
    return removed


# This function validates the minimum config shape required by Step 21.
# It checks the experiment paths, Snort execution settings, detector rule toggles, and detector policy label.
# The rules_policy_path is optional, but when present it must be a string so it can be injected safely into the Snort Lua override.
def validate_config(config: dict[str, Any]) -> None:
    require_keys(config, ["experiment", "snort", "pipeline"], "config")
    require_keys(config["experiment"], ["experiment_id", "output_root"], "experiment")
    require_keys(
        config["snort"],
        ["snort_binary", "config_path", "plugin_path", "daq_dir", "enable_builtin_rules", "enable_ruleset", "ruleset_path"],
        "snort",
    )

    snort = config["snort"]
    if not isinstance(snort["enable_builtin_rules"], bool):
        raise ValueError("snort.enable_builtin_rules must be true or false.")
    if not isinstance(snort["enable_ruleset"], bool):
        raise ValueError("snort.enable_ruleset must be true or false.")
    if snort["enable_ruleset"] and not str(snort.get("ruleset_path", "")).strip():
        raise ValueError("snort.ruleset_path must be set when snort.enable_ruleset is true.")
    if not str(snort.get("plugin_path", "")).strip():
        raise ValueError("snort.plugin_path must be set because Snort needs the plugin path for this benchmark setup.")
    if not str(snort.get("daq_dir", "")).strip():
        raise ValueError("snort.daq_dir must be set because Snort needs the DAQ directory for this benchmark setup.")
    if not isinstance(snort.get("rules_policy_path", ""), str):
        raise ValueError("snort.rules_policy_path must be a string when provided.")
    if "detector_policy_label" in snort:
        detector_policy_label = snort["detector_policy_label"]
        if not isinstance(detector_policy_label, str):
            raise ValueError("snort.detector_policy_label must be a string when provided.")
        if not sanitize_name_component(detector_policy_label):
            raise ValueError("snort.detector_policy_label must not be empty when provided.")
    if "snaplen" in snort:
        snaplen = snort["snaplen"]
        if not isinstance(snaplen, int) or isinstance(snaplen, bool) or snaplen <= 0:
            raise ValueError("snort.snaplen must be a positive integer when provided.")



# This function returns the detector policy label used to partition Step 21 Snort artifacts.
# It is a directory/metadata label, not the Snort .states path itself.
def detector_policy_label_from_config(config: dict[str, Any]) -> str:
    snort_config = config["snort"]
    detector_policy_label = str(snort_config.get("detector_policy_label", "")).strip()
    if detector_policy_label:
        return sanitize_name_component(detector_policy_label)

    rules_policy_path = str(snort_config.get("rules_policy_path", "")).strip()
    if rules_policy_path:
        policy_stem = Path(expand_config_path(rules_policy_path)).stem
        policy_stem = policy_stem.removeprefix("rulestates-")
        return sanitize_name_component(policy_stem)

    return "none"


# This function returns the default input PCAP for either PRE or POST traffic.
# PRE and POST traffic are both resolved inside the single experiment workspace.
def default_input_pcap(
    config: dict[str, Any],
    traffic_version: str,
    experiment_root_override: str | Path | None = None,
) -> Path:
    experiment_root = Path(experiment_root_override).expanduser() if experiment_root_override else build_experiment_root(config)
    if traffic_version == "pre":
        return experiment_root / "03_selected_traffic" / "selected_malicious_traffic.pcap"
    return experiment_root / "10_reconstructed_pcap" / "modified_traffic.pcap"


# This function returns the default Step 21 output directory for a Snort run.
# PRE artifacts are common only within the selected detector policy, while POST artifacts are additionally separated by execution timestamp.
def default_output_dir(
    config: dict[str, Any],
    traffic_version: str,
    detector_policy_label: str,
    post_run_label: str | None,
    experiment_root_override: str | Path | None = None,
) -> Path:
    experiment_root = Path(experiment_root_override).expanduser() if experiment_root_override else build_experiment_root(config)
    detector_root = experiment_root / "11_snort_raw" / detector_policy_label
    if traffic_version == "pre":
        return detector_root / "pre"
    if not post_run_label:
        raise ValueError("post_run_label must be provided for POST Step 21 output directories.")
    return detector_root / "post" / post_run_label


# This function builds the inline Lua ips table passed to Snort through --lua.
# It keeps the base snort.lua file stable while letting the pipeline config control built-in rules, the external ruleset include, and the optional Cisco policy states file.
def build_lua_ips_config(snort_config: dict[str, Any]) -> str:
    parts = [
        "variables = default_variables",
        f"enable_builtin_rules = {str(snort_config['enable_builtin_rules']).lower()}",
    ]
    if snort_config["enable_ruleset"]:
        ruleset_path = expand_config_path(snort_config["ruleset_path"])
        parts.append(f"include = '{ruleset_path}'")
        rules_policy_path = str(snort_config.get("rules_policy_path", "")).strip()
        if rules_policy_path:
            parts.append(f"states = '{expand_config_path(rules_policy_path)}'")
    return "ips = { " + ", ".join(parts) + " }"


# This function expands user-home references without converting Ubuntu-style absolute paths into Windows-style paths.
# The pipeline config is intended for the Ubuntu VM, so paths such as /usr/local/bin/snort must be preserved when inspected from Windows.
def expand_config_path(raw_path: str) -> str:
    return os.path.expanduser(str(raw_path))


# This function constructs the Snort command as an argv list.
# The command runs Snort over one PCAP, writes logs under output_dir, disables checksum validation with -k none, and injects the detector configuration through --lua.
def build_snort_command(
    *,
    snort_config: dict[str, Any],
    input_pcap_path: Path,
    output_dir: Path,
) -> list[str]:
    command = [
        expand_config_path(snort_config["snort_binary"]),
        "-c",
        expand_config_path(snort_config["config_path"]),
    ]
    command.extend(["--plugin-path", expand_config_path(snort_config["plugin_path"])])
    command.extend(["--daq-dir", expand_config_path(snort_config["daq_dir"])])
    command.extend(
        [
            "-l",
            str(output_dir),
            "-k",
            "none",
            "-r",
            str(input_pcap_path),
            "--lua",
            build_lua_ips_config(snort_config),
        ]
    )
    snaplen = snort_config.get("snaplen")
    if snaplen is not None:
        command.extend(["--snaplen", str(snaplen)])
    return command


# This function writes a UTF-8 text artifact and creates its parent directory if needed.
def write_text(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


# This function runs an external command while teeing its stdout and stderr to the active terminal streams.
# The same output is also returned so Step 21 can preserve Snort's stdout.log and stderr.log artifacts.
def run_subprocess_with_tee(command: list[str]) -> tuple[str, str, int]:
    completed = subprocess.Popen(
        command,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        text=True,
        bufsize=1,
    )
    stdout_chunks: list[str] = []
    stderr_chunks: list[str] = []

    def tee_stream(source: Any, destination: Any, chunks: list[str]) -> None:
        for line in source:
            chunks.append(line)
            destination.write(line)
            destination.flush()
        source.close()

    stdout_thread = threading.Thread(target=tee_stream, args=(completed.stdout, sys.stdout, stdout_chunks))
    stderr_thread = threading.Thread(target=tee_stream, args=(completed.stderr, sys.stderr, stderr_chunks))
    stdout_thread.start()
    stderr_thread.start()
    exit_code = completed.wait()
    stdout_thread.join()
    stderr_thread.join()
    return "".join(stdout_chunks), "".join(stderr_chunks), exit_code


# This function returns the ruleset value used in the converted alert JSON filename.
# If the ruleset is disabled, the filename records that explicitly; otherwise it records the configured ruleset file stem.
def ruleset_label(snort_config: dict[str, Any]) -> str:
    if not snort_config["enable_ruleset"]:
        return "off"
    ruleset_path = expand_config_path(snort_config["ruleset_path"])
    return sanitize_name_component(Path(ruleset_path).stem)


# This function returns the policy value used in the converted alert JSON filename.
# Cisco policy state files are named rulestates-*.states, so the prefix is removed to keep filenames shorter.
def rules_policy_label(snort_config: dict[str, Any]) -> str:
    rules_policy_path = str(snort_config.get("rules_policy_path", "")).strip()
    if not snort_config["enable_ruleset"] or not rules_policy_path:
        return "none"
    policy_stem = Path(expand_config_path(rules_policy_path)).stem
    policy_stem = policy_stem.removeprefix("rulestates-")
    return sanitize_name_component(policy_stem)


# This function returns whether Snort built-in inspector rules were enabled for the run.
def builtin_label(snort_config: dict[str, Any]) -> str:
    return "on" if snort_config["enable_builtin_rules"] else "off"


# This function formats one filename field as name-value.
# Complete fields are later separated with double underscores to avoid ambiguity when values contain dashes.
def filename_field(name: str, value: str) -> str:
    return f"{sanitize_name_component(name)}-{sanitize_name_component(value)}"


# This function builds the human-readable converted alert JSON filename.
# The filename records traffic side, PCAP stem, ruleset, policy, and built-in rule state.
def converted_alert_json_name(
    *,
    traffic_version: str,
    input_pcap_path: Path,
    snort_config: dict[str, Any],
) -> str:
    parts = [
        "alerts",
        filename_field("traffic", traffic_version),
    ]
    parts.extend(
        [
            filename_field("pcap", input_pcap_path.stem),
            filename_field("ruleset", ruleset_label(snort_config)),
            filename_field("policy", rules_policy_label(snort_config)),
            filename_field("builtin", builtin_label(snort_config)),
        ]
    )
    return "__".join(parts) + ".json"


# This function converts Snort alert_json.txt content from JSONL into a JSON array.
# The raw alert_json.txt file is left untouched, and parse errors are reported in metadata instead of silently dropping lines.
def convert_alert_jsonl_to_json_array(source_path: Path, output_path: Path) -> dict[str, Any]:
    alerts = []
    errors = []
    with source_path.open("r", encoding="utf-8") as source_file:
        for line_number, line in enumerate(source_file, start=1):
            stripped = line.strip()
            if not stripped:
                continue
            try:
                alerts.append(json.loads(stripped))
            except json.JSONDecodeError as error:
                errors.append(
                    {
                        "line_number": line_number,
                        "error": str(error),
                    }
                )

    if errors:
        return {
            "source": str(source_path),
            "converted": None,
            "alert_count": len(alerts),
            "status": "failed",
            "errors": errors,
        }

    write_json(output_path, alerts)
    return {
        "source": str(source_path),
        "converted": str(output_path),
        "alert_count": len(alerts),
        "status": "converted",
        "errors": [],
    }


# This function post-processes Snort's alert_json.txt output when it exists.
# It preserves the raw JSONL file and creates a separate JSON array file for easier human inspection.
def postprocess_snort_alert_json(
    *,
    output_dir: Path,
    traffic_version: str,
    input_pcap_path: Path,
    snort_config: dict[str, Any],
) -> dict[str, Any]:
    raw_alert_path = output_dir / "alert_json.txt"
    if not raw_alert_path.exists():
        return {
            "source": str(raw_alert_path),
            "converted": None,
            "alert_count": 0,
            "status": "source_not_found",
            "errors": [],
        }

    converted_path = output_dir / converted_alert_json_name(
        traffic_version=traffic_version,
        input_pcap_path=input_pcap_path,
        snort_config=snort_config,
    )
    return convert_alert_jsonl_to_json_array(raw_alert_path, converted_path)


# This function executes one Snort run or prepares one dry-run.
# It stores command evidence, stdout/stderr logs, converted alert JSON artifacts, and structured execution metadata even if Snort exits with a non-zero code.
def run_one_snort_execution(
    *,
    config: dict[str, Any],
    traffic_version: str,
    detector_policy_label: str,
    post_run_label: str | None,
    input_pcap_path: Path,
    output_dir: Path,
    experiment_root: Path,
    dry_run: bool,
) -> dict[str, Any]:
    if not input_pcap_path.exists():
        raise FileNotFoundError(f"Input PCAP does not exist: {input_pcap_path}")

    if dry_run:
        assert_path_inside_experiment_root(output_dir, experiment_root)
        output_dir.mkdir(parents=True, exist_ok=True)
        removed_output_artifacts: list[str] = []
    else:
        removed_output_artifacts = prepare_clean_output_dir(output_dir, experiment_root)
    snort_config = config["snort"]
    command = build_snort_command(snort_config=snort_config, input_pcap_path=input_pcap_path, output_dir=output_dir)
    command_json = {
        "argv": command,
        "shell_escaped_hint": " ".join(json.dumps(part) for part in command),
    }

    started_at = utc_now()
    completed_at = started_at
    stdout = ""
    stderr = ""
    exit_code: int | None = None

    traffic_scope = "pre" if traffic_version == "pre" else "post"
    print(f"[{traffic_version}] scope={traffic_scope} dry_run={dry_run}")
    print(f"[{traffic_version}] detector_policy_label={detector_policy_label}")
    print(f"[{traffic_version}] post_run_label={post_run_label or 'null'}")
    print(f"[{traffic_version}] input_pcap={input_pcap_path}")
    print(f"[{traffic_version}] output_dir={output_dir}")
    print(f"[{traffic_version}] cleaned_output_artifacts={len(removed_output_artifacts)}")
    for removed_artifact in removed_output_artifacts:
        print(f"[{traffic_version}] cleaned_output_artifact={removed_artifact}")
    print(f"[{traffic_version}] snort_binary={expand_config_path(snort_config['snort_binary'])}")
    print(f"[{traffic_version}] snort_config_path={expand_config_path(snort_config['config_path'])}")
    print(f"[{traffic_version}] plugin_path={expand_config_path(snort_config['plugin_path'])}")
    print(f"[{traffic_version}] daq_dir={expand_config_path(snort_config['daq_dir'])}")
    print(f"[{traffic_version}] snaplen={snort_config.get('snaplen') or 'default'}")
    print(f"[{traffic_version}] enable_ruleset={snort_config['enable_ruleset']}")
    print(f"[{traffic_version}] enable_builtin_rules={snort_config['enable_builtin_rules']}")
    print(f"[{traffic_version}] ruleset_path={expand_config_path(snort_config['ruleset_path']) if snort_config['enable_ruleset'] else 'disabled'}")
    print(f"[{traffic_version}] rules_policy_path={expand_config_path(snort_config.get('rules_policy_path', '')) or 'none'}")
    print(f"[{traffic_version}] command={command_json['shell_escaped_hint']}")

    if not dry_run:
        stdout, stderr, exit_code = run_subprocess_with_tee(command)
        completed_at = utc_now()

    write_json(output_dir / "command.json", command_json)
    write_text(output_dir / "stdout.log", stdout)
    write_text(output_dir / "stderr.log", stderr)
    if dry_run:
        alert_postprocessing = {
            "source": str(output_dir / "alert_json.txt"),
            "converted": None,
            "alert_count": 0,
            "status": "not_run",
            "errors": [],
        }
    else:
        alert_postprocessing = postprocess_snort_alert_json(
            output_dir=output_dir,
            traffic_version=traffic_version,
            input_pcap_path=input_pcap_path,
            snort_config=snort_config,
        )

    metadata = {
        "schema_version": RUN_SCHEMA_VERSION,
        "generated_at_utc": utc_now(),
        "started_at_utc": started_at,
        "completed_at_utc": completed_at,
        "dry_run": dry_run,
        "exit_code": exit_code,
        "experiment_id": config["experiment"]["experiment_id"],
        "config_source": config.get("_config_path", ""),
        "traffic_version": traffic_version,
        "traffic_scope": traffic_scope,
        "detector_policy_label": detector_policy_label,
        "post_run_label": post_run_label,
        "input_pcap": str(input_pcap_path),
        "output_dir": str(output_dir),
        "cleaned_output_artifacts": removed_output_artifacts,
        "snort_binary": expand_config_path(snort_config["snort_binary"]),
        "snort_config_path": expand_config_path(snort_config["config_path"]),
        "plugin_path": expand_config_path(snort_config["plugin_path"]),
        "daq_dir": expand_config_path(snort_config["daq_dir"]),
        "snaplen": snort_config.get("snaplen"),
        "enable_builtin_rules": snort_config["enable_builtin_rules"],
        "enable_ruleset": snort_config["enable_ruleset"],
        "ruleset_path": expand_config_path(snort_config["ruleset_path"]) if snort_config["enable_ruleset"] else "",
        "rules_policy_path": (
            expand_config_path(snort_config.get("rules_policy_path", ""))
            if snort_config["enable_ruleset"] and str(snort_config.get("rules_policy_path", "")).strip()
            else ""
        ),
        "alert_output_mode": "alert_json",
        "alert_output_source": "snort_lua_config",
        "alert_json_postprocessing": alert_postprocessing,
        "artifacts": {
            "command": str(output_dir / "command.json"),
            "stdout": str(output_dir / "stdout.log"),
            "stderr": str(output_dir / "stderr.log"),
            "metadata": str(output_dir / "execution_metadata.json"),
            "raw_alert_jsonl": alert_postprocessing["source"],
            "converted_alert_json": alert_postprocessing["converted"],
        },
    }
    write_json(output_dir / "execution_metadata.json", metadata)
    print(f"[{traffic_version}] exit_code={exit_code}")
    print(f"[{traffic_version}] stdout_log={output_dir / 'stdout.log'} bytes={len(stdout.encode('utf-8'))}")
    print(f"[{traffic_version}] stderr_log={output_dir / 'stderr.log'} bytes={len(stderr.encode('utf-8'))}")
    print(f"[{traffic_version}] command_json={output_dir / 'command.json'}")
    print(f"[{traffic_version}] metadata_json={output_dir / 'execution_metadata.json'}")
    print(
        f"[{traffic_version}] alert_json_status={alert_postprocessing['status']} "
        f"alert_count={alert_postprocessing['alert_count']} "
        f"converted={alert_postprocessing['converted'] or 'null'}"
    )
    return metadata


# This function is the public Python entry point for Step 21.
# It loads and validates the config, resolves PRE/POST paths, and runs Snort once or twice depending on the requested traffic version.
def run_snort(
    *,
    config_path: str | Path,
    traffic_version: str,
    input_pcap: str | Path | None,
    output_dir: str | Path | None,
    experiment_root: str | Path | None,
    dry_run: bool,
) -> list[dict[str, Any]]:
    config = load_json_config(config_path)
    validate_config(config)

    detector_policy_label = detector_policy_label_from_config(config)
    resolved_experiment_root = Path(experiment_root).expanduser() if experiment_root else build_experiment_root(config)
    runs: list[dict[str, Any]] = []
    selected_versions = ["pre", "post"] if traffic_version == "both" else [traffic_version]
    post_run_label = f"run-{utc_minute_timestamp_for_path()}" if "post" in selected_versions else None
    for selected_version in selected_versions:
        run_post_label = post_run_label if selected_version == "post" else None
        resolved_input = (
            Path(input_pcap).expanduser()
            if input_pcap and len(selected_versions) == 1
            else default_input_pcap(config, selected_version, resolved_experiment_root)
        )
        resolved_output_dir = (
            Path(output_dir).expanduser()
            if output_dir and len(selected_versions) == 1
            else default_output_dir(config, selected_version, detector_policy_label, run_post_label, resolved_experiment_root)
        )
        runs.append(
            run_one_snort_execution(
                config=config,
                traffic_version=selected_version,
                detector_policy_label=detector_policy_label,
                post_run_label=run_post_label,
                input_pcap_path=resolved_input,
                output_dir=resolved_output_dir,
                experiment_root=resolved_experiment_root,
                dry_run=dry_run,
            )
        )
    return runs


# This function resolves the terminal log path for Step 21.
# Terminal logs are grouped by detector policy and the requested traffic execution scope, while POST raw artifacts are separated by post_run_label.
def resolve_log_path(args: argparse.Namespace) -> Path:
    if args.log_file:
        return Path(args.log_file).expanduser()

    config = load_json_config(args.config)
    validate_config(config)
    experiment_root = Path(args.experiment_root).expanduser() if args.experiment_root else build_experiment_root(config)
    detector_policy_label = detector_policy_label_from_config(config)
    branch_label = str(Path(detector_policy_label) / f"{args.traffic_version}-traffic")
    return default_step_log_path(
        experiment_root=experiment_root,
        step_name="step_21_snort_runner",
        branch_label=branch_label,
        filename_prefix="step_21_snort_runner",
    )


# This function parses command-line arguments for Step 21.
# The ruleset, policy, and built-in rule settings are intentionally read from the config rather than from CLI flags.
def parse_cli_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Run Snort 3 over Step 21 PRE and POST PCAP artifacts.")
    add = parser.add_argument
    add("--config", required=True, help="Path to the experiment JSON config.")
    add("--traffic-version", choices=["pre", "post", "both"], default="both", help="Traffic side to run.")
    add("--input-pcap", help="Explicit PCAP path. Only valid for a single resolved run.")
    add("--output-dir", help="Explicit output directory. Only valid for a single resolved run.")
    add("--log-file", help="Optional explicit terminal log file path.")
    add(
        "--experiment-root",
        help=(
            "Optional experiment root override. Useful when the VM artifact root differs from "
            "experiment.output_root in the config."
        ),
    )
    add("--dry-run", action="store_true", help="Write command and metadata without executing Snort.")
    return parser.parse_args()


# This function is the command-line entry point.
# It rejects input/output overrides for traffic-version both because one override cannot safely represent both PRE and POST runs.
def main() -> None:
    args = parse_cli_args()
    if (args.input_pcap or args.output_dir) and args.traffic_version == "both":
        raise ValueError("--input-pcap and --output-dir overrides are only valid for one resolved run.")

    log_path = resolve_log_path(args)
    with terminal_log(log_path, banner="Step 21 terminal log"):
        try:
            runs = run_snort(
                config_path=args.config,
                traffic_version=args.traffic_version,
                input_pcap=args.input_pcap,
                output_dir=args.output_dir,
                experiment_root=args.experiment_root,
                dry_run=args.dry_run,
            )
        except Exception:
            print("Step 21 failed. Traceback follows:", file=sys.stderr)
            traceback.print_exc()
            raise SystemExit(1)

        for run in runs:
            print(
                f"{run['traffic_version']} {run['detector_policy_label']} {run['traffic_scope']}: "
                f"exit_code={run['exit_code']} output_dir={run['output_dir']}"
            )


if __name__ == "__main__":
    main()
